### ISSUE TITLE
Output to directory

### ISSUE THREAD

**Issue by thoroc** [tomasbjerre/plantuml-cli#1]
The output option doesn't respect the tree structure of the input when using wildcard:

This creates the png right next to the src files
```sh
npx plantuml-cli -tpng docs/diagrams/src/**/*.puml
```

This creates the png in a unique output directory
```sh
npx plantuml-cli -tpng docs/diagrams/src/**/*.puml -o docs/diagrams/img
```

That does some weird duplication in the input tree directory
```sh
npx plantuml-cli -tpng docs/diagrams/src/**/*.puml -o ../../docs/diagrams/img
```

Is this a bug?

**Comment by tomasbjerre** [comment]
Is this a problem only when using this wrapper? Or also when using the jar from https://github.com/plantuml/plantuml ?

**Comment by thoroc** [comment]
I need to double check that. Just looking at the moment at the official plantuml docs.

**Comment by thoroc** [comment]
Ok that's an issue with plantuml; I have reproduced the issue with plantuml called directly.
